

package com.axeldev.login.igu;

import com.axeldev.login.logica.Controladora;
import com.axeldev.login.logica.Rol;
import com.axeldev.login.logica.Usuario;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


public class EdicionUsuarios extends javax.swing.JFrame {

    Controladora control = null;
    int id_user;
    Usuario user;
    
    /** Creates new form EdicionUsuarios */
    public EdicionUsuarios(Controladora control, int id_user) {
        initComponents();
        this.control = control;
        this.id_user = id_user;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerEdicionUsuario = new javax.swing.JPanel();
        labelEdicionUser = new javax.swing.JLabel();
        containerTxtAndBtns = new javax.swing.JPanel();
        labelNombreUser = new javax.swing.JLabel();
        labelPasswordUser = new javax.swing.JLabel();
        labelRolUser = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtNombre = new javax.swing.JTextField();
        cbRol = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelEdicionUser.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelEdicionUser.setText("Edicion de Usuarios");

        containerTxtAndBtns.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNombreUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombreUser.setText("Nombre:");

        labelPasswordUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPasswordUser.setText("Contraseña:");

        labelRolUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelRolUser.setText("Rol:");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cbRol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerTxtAndBtnsLayout = new javax.swing.GroupLayout(containerTxtAndBtns);
        containerTxtAndBtns.setLayout(containerTxtAndBtnsLayout);
        containerTxtAndBtnsLayout.setHorizontalGroup(
            containerTxtAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTxtAndBtnsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(containerTxtAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerTxtAndBtnsLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(containerTxtAndBtnsLayout.createSequentialGroup()
                        .addComponent(labelPasswordUser)
                        .addGap(18, 18, 18)
                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                    .addGroup(containerTxtAndBtnsLayout.createSequentialGroup()
                        .addComponent(labelRolUser)
                        .addGap(18, 18, 18)
                        .addComponent(cbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(containerTxtAndBtnsLayout.createSequentialGroup()
                        .addComponent(labelNombreUser)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre)))
                .addContainerGap())
        );
        containerTxtAndBtnsLayout.setVerticalGroup(
            containerTxtAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTxtAndBtnsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerTxtAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreUser)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerTxtAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPasswordUser)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerTxtAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRolUser)
                    .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(containerTxtAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerEdicionUsuarioLayout = new javax.swing.GroupLayout(containerEdicionUsuario);
        containerEdicionUsuario.setLayout(containerEdicionUsuarioLayout);
        containerEdicionUsuarioLayout.setHorizontalGroup(
            containerEdicionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerEdicionUsuarioLayout.createSequentialGroup()
                .addGroup(containerEdicionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerEdicionUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(containerTxtAndBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerEdicionUsuarioLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(labelEdicionUser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerEdicionUsuarioLayout.setVerticalGroup(
            containerEdicionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerEdicionUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEdicionUser)
                .addGap(18, 18, 18)
                .addComponent(containerTxtAndBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerEdicionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerEdicionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String usuario = txtNombre.getText();
        String password = txtPassword.getText();
        String rol = (String) cbRol.getSelectedItem();

        control.editarUsuario(user,usuario, password, rol);

        mostrarMensaje("Usuario editado correctamente.", "Info", "Edición exitosa.");
        
        this.dispose();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNombre.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        user = control.traerUsuario(id_user);
        if(user != null){
            txtNombre.setText(user.getUsuario());
            txtPassword.setText(user.getPassword());
            
            List<Rol> roles = control.traerRoles();

            if (roles != null) {
                for (Rol role : roles) {
                    cbRol.addItem(role.getNombre());
                }
            }
           
            String rol = user.getRol().getNombre();
            
            int items = cbRol.getItemCount();
            
            for (int index = 0; index < items; index++) {
                if(String.valueOf(cbRol.getItemAt(index)).equals(rol)){
                    cbRol.setSelectedIndex(index);
                }
            }
        }
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JPanel containerEdicionUsuario;
    private javax.swing.JPanel containerTxtAndBtns;
    private javax.swing.JLabel labelEdicionUser;
    private javax.swing.JLabel labelNombreUser;
    private javax.swing.JLabel labelPasswordUser;
    private javax.swing.JLabel labelRolUser;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    public void mostrarMensaje(String mensaje, String tipo, String titulos) {
        JOptionPane optionPane = new JOptionPane(mensaje);
        if (tipo.equals("Info")) {
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        } else if (tipo.equals("Error")) {
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulos);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }
    
}
