

package com.axeldev.login.igu;

import com.axeldev.login.logica.Controladora;
import com.axeldev.login.logica.Usuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class PrincipalUser extends javax.swing.JFrame {

    Controladora control = null;
    Usuario user = null;
    
    /** Creates new form PrincipalUser */
    public PrincipalUser(Controladora control, Usuario user) {
        initComponents();
        this.control = control;
        this.user = user;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPrincipalUser = new javax.swing.JPanel();
        labelTitleUser = new javax.swing.JLabel();
        containerTable = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();
        btnActualizarTablaUsuario = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelTitleUser.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitleUser.setText("Sistema administrador de usuarios");

        containerTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        containerTable.setViewportView(tableUsers);

        btnActualizarTablaUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizarTablaUsuario.setText("Actualizar Tabla");
        btnActualizarTablaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaUsuarioActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtUser.setEditable(false);
        txtUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtUser.setBorder(null);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerPrincipalUserLayout = new javax.swing.GroupLayout(containerPrincipalUser);
        containerPrincipalUser.setLayout(containerPrincipalUserLayout);
        containerPrincipalUserLayout.setHorizontalGroup(
            containerPrincipalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPrincipalUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPrincipalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerTable, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitleUser))
                .addGap(49, 49, 49)
                .addGroup(containerPrincipalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUser)
                    .addComponent(btnActualizarTablaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerPrincipalUserLayout.setVerticalGroup(
            containerPrincipalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPrincipalUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPrincipalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitleUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerPrincipalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerTable, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addGroup(containerPrincipalUserLayout.createSequentialGroup()
                        .addComponent(btnActualizarTablaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPrincipalUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPrincipalUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        //txtUser.setText(user.getUsuario());
    }//GEN-LAST:event_txtUserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.txtUser.setText(user.getUsuario());
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnActualizarTablaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaUsuarioActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnActualizarTablaUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTablaUsuario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel containerPrincipalUser;
    private javax.swing.JScrollPane containerTable;
    private javax.swing.JLabel labelTitleUser;
    private javax.swing.JTable tableUsers;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        String titulos[] = {
            "Id",
            "Nombre",
            "Rol"
        };
        modeloTabla.setColumnIdentifiers(titulos);
        
        List<Usuario> usuarios = control.traerUsuarios();
        if(usuarios != null){
            for (Usuario usuario : usuarios) {
                Object[] objeto = {
                    usuario.getId(),
                    usuario.getUsuario(),
                    usuario.getRol().getNombre()
                };
                modeloTabla.addRow(objeto);
            }
        }
        
        tableUsers.setModel(modeloTabla);
    }

}
